// eslint.config.js — AUTO-GENERATED by claude-resources/tools/sync-thesis-eslint.js
// DO NOT EDIT directly. Change the source in claude-resources/tools/eslint-config-thesis/
// Re-sync: node claude-resources/tools/sync-thesis-eslint.js (from development/)
import tsParser from '@typescript-eslint/parser'
import { thesisConfig } from '@thesis/eslint-config'

export default thesisConfig(tsParser)
